apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: addressbook
  name: addressbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: addressbook
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: addressbook
    spec:
      containers:
      - image: gcr.io/project2-363320/addressbook1:0.1.18
        name: addressbook
        ports:
            - containerPort: 8080
              protocol: TCP
